export const updateTimelineItemActivitySecondsKey = Symbol(String | Number)
export const timelineItemsKey = Symbol(String | Number)
export const activitySelectOptionsKey = Symbol(String | Number)
export const periodSelectOptionsKey = Symbol(String | Number)
export const setTimelineItemActivityKey = Symbol(String | Number)
export const setActivitySecondsToCompleteKey = Symbol(String | Number)
export const createActivityKey = Symbol(String | Number)
export const deleteActivityKey = Symbol(String | Number)
